/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: David Zerba (https://sketchfab.com/DavidZerba)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coffee-shop-cup-37e6805f2b7a4158a1d61fe75f8e2a33
Title: Coffee Shop Cup
*/

import { useGLTF } from '@react-three/drei'

export function CoffeeShopCup(props) {
  const { nodes, materials } = useGLTF('/coffee_shop_cup.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.233}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 2.439, 0]} scale={[1.573, 2.439, 1.573]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_5.geometry}
              material={materials.material}
              position={[-0.001, -0.083, 0]}
              scale={[0.636, 0.41, 0.636]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_7.geometry}
              material={materials.material_1}
              position={[0, 0.724, -0.001]}
              rotation={[0, -Math.PI / 2, 0]}
              scale={[1.036, 0.628, 1.036]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_9.geometry}
              material={materials.Sleeve}
              position={[-0.001, -1, 0]}
              scale={[0.636, 0.41, 0.636]}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/coffee_shop_cup.glb')