/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: LightSwitch (https://sketchfab.com/edwardlewis450)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/metal-fork-high-res-e98e7fb33743442383812b68608f7006
Title: Metal Fork - High Res
*/

import { useGLTF } from '@react-three/drei'

export function Fork(props) {
  const { nodes, materials } = useGLTF('/metal_fork_-_high_res.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials['Material.001']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/metal_fork_-_high_res.glb')