/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: mfhscoobydoo (https://sketchfab.com/mfhscoobydoo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/realtime-grass-07d38555cae844f7abdeace9d19c4777
Title: Realtime Grass
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function GrassReal(props) {
  const { nodes, materials } = useGLTF('/realtime_grass_compressed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.009}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_Material_0.geometry}
            material={materials.Material}
            position={[-109.609, 30.611, -24.277]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={800}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plate1001_Plate1_0.geometry}
            material={materials.Plate1}
            position={[90.757, -1.13, 0]}
            rotation={[Math.PI / 2, 1.421, -Math.PI / 2]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plate2001_Plate2_0.geometry}
            material={materials.Plate2}
            position={[90.757, -1.13, -266.684]}
            rotation={[Math.PI / 2, 1.421, -Math.PI / 2]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plate3001_Plate3_0.geometry}
            material={materials.Plate3}
            position={[90.757, -1.13, -533.369]}
            rotation={[Math.PI / 2, 1.421, -Math.PI / 2]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plate3_Plate3_0.geometry}
            material={materials.Plate3}
            position={[-146.762, -1.585, -533.369]}
            rotation={[0, Math.PI / 2, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plate2_Plate2_0.geometry}
            material={materials.Plate2}
            position={[-146.762, -1.585, -266.684]}
            rotation={[0, Math.PI / 2, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plate1_Plate1_0.geometry}
            material={materials.Plate1}
            position={[-146.762, -1.585, 0]}
            rotation={[0, Math.PI / 2, 0]}
            scale={100}
          />
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plate1003_Plate1_0.geometry}
        material={materials.Plate1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plate2003_Plate2_0.geometry}
        material={materials.Plate2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plate3003_Plate3_0.geometry}
        material={materials.Plate3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plate3002_Plate3_0.geometry}
        material={materials.Plate3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plate2002_Plate2_0.geometry}
        material={materials.Plate2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plate1002_Plate1_0.geometry}
        material={materials.Plate1}
      />
    </group>
  )
}

useGLTF.preload('/realtime_grass_compressed.glb')

