/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Sam3D (https://sketchfab.com/samuelcrevier12)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/grass-low-poly-3d-scan-ff850d5812c24c1aaf31955396e95144
Title: Grass low poly 3d scan
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function GrassLowPoly(props) {
  const { nodes, materials } = useGLTF('/grass_low_poly_3d_scan_optimized.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_0_Material_0_0.geometry}
          material={materials.Material_0}
          position={[0, 45.257, 0]}
          rotation={[-1.675, -0.039, -0.201]}
          scale={100}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/grass_low_poly_3d_scan_optimized.glb')