/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: artfletch (https://sketchfab.com/artfletch)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-old-curiosity-shop-2024-1935a437b1e6457eb6c6b66034454664
Title: The Old Curiosity Shop 2024
*/

import { useGLTF } from '@react-three/drei'

export function OldCuriosity(props) {
  const { nodes, materials } = useGLTF('/the_old_curiosity_shop_2024.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={
            materials.TheOldCuriosityShop2024_01_Model_6TheOldCuriosityShop2024_01_Model_6_u1_v1
          }
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.phong1SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={
            materials.TheOldCuriosityShop2024_01_Model_7TheOldCuriosityShop2024_01_Model_7_u1_v1
          }
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={
            materials.TheOldCuriosityShop2024_01_Model_7TheOldCuriosityShop2024_01_Model_7_u1_v1
          }
        />
      </group>
    </group>
  )
}

useGLTF.preload('/the_old_curiosity_shop_2024.glb')

