/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Anserkon (https://sketchfab.com/anserkon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wood-picnic-table-887796ef013c42c9837320edaa316d07
Title: Wood Picnic Table
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function PicnicTable(props) {
  const { nodes, materials } = useGLTF('/wood_picnic_table.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.material}
        position={[1.881, 0.522, 0.5]}
        scale={[0.035, 0.5, 0.512]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials['.001']}
        position={[1.904, 0.808, 0.44]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.036, 0.054, 0.036]}
      />
    </group>
  )
}

useGLTF.preload('/wood_picnic_table.glb')

