/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Johana-PS (https://sketchfab.com/Johana-PS)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cake-3d-756da5ef6d0249479510e6bdd1856e42
Title: Cake 3D
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function PinkCake(props) {
  const { nodes, materials } = useGLTF('/cake_3d.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[3.324, -1.165, 0.226]} scale={0.301}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.Cream}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.Cream}
          position={[-10.895, 0.046, -13.109]}
          rotation={[-Math.PI, 1.204, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials.Cream}
          position={[-11.837, 0.308, 11.324]}
          rotation={[0.137, 0.012, -0.15]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials.Cream}
          position={[-23.941, 0, -2.1]}
          rotation={[-Math.PI, -0.628, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_14.geometry}
          material={materials.Cream}
          position={[-3.369, 0, 6.91]}
          rotation={[0, 1.454, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16.geometry}
          material={materials.Cream}
          position={[-2.661, 0.227, -8.3]}
          rotation={[2.726, -0.939, 2.794]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_18.geometry}
          material={materials.Cream}
          position={[-20.178, 0, 8.68]}
          rotation={[0.141, -1.489, 0.153]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_20.geometry}
          material={materials.Cream}
          position={[-20.22, 0, -9.731]}
          rotation={[Math.PI, -1.382, Math.PI]}
        />
      </group>
      <group position={[-0.285, 0, -0.026]} scale={[3.036, 1.205, 3.036]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_22.geometry}
          material={materials.Cake}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_23.geometry}
          material={materials.Band}
        />
        <group position={[0.948, 0.438, -0.242]} scale={[0.055, 0.14, 0.055]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_25.geometry}
            material={materials.Band}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_27.geometry}
            material={materials.Band}
            position={[-2.771, -3.01, -5.724]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_29.geometry}
            material={materials.Band}
            position={[-6.881, 0.136, -9.906]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_31.geometry}
            material={materials.Band}
            position={[-17.489, 0.552, -13.399]}
            rotation={[0, 1.119, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_33.geometry}
            material={materials.Band}
            position={[-25.306, -3.275, -11.543]}
            rotation={[0, 1.119, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_35.geometry}
            material={materials.Band}
            position={[-30.401, 0.351, -7.559]}
            rotation={[0, 1.119, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_37.geometry}
            material={materials.Band}
            position={[-11.955, -3.562, -12.132]}
            rotation={[0, 1.119, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_39.geometry}
            material={materials.Band}
            position={[-30.049, -0.355, 16.685]}
            rotation={[-Math.PI, -0.482, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_41.geometry}
            material={materials.Band}
            position={[-25.02, -3.364, 20.436]}
            rotation={[-Math.PI, -0.482, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_43.geometry}
            material={materials.Band}
            position={[-19.509, -0.218, 21.917]}
            rotation={[-Math.PI, -0.482, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_45.geometry}
            material={materials.Band}
            position={[-8.278, 0.115, 19.706]}
            rotation={[0, -1.54, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_47.geometry}
            material={materials.Band}
            position={[-2.923, -3.726, 15.015]}
            rotation={[0, -1.54, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_49.geometry}
            material={materials.Band}
            position={[-0.69, -0.19, 10.842]}
            rotation={[0, -1.54, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_51.geometry}
            material={materials.Band}
            position={[-13.912, -3.916, 21.858]}
            rotation={[0, -1.54, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_53.geometry}
            material={materials.Band}
            position={[0.612, -3.261, 5.447]}
            rotation={[0, -1.54, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_55.geometry}
            material={materials.Band}
            position={[-33.731, -2.67, 10.878]}
            rotation={[-Math.PI, -0.482, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_57.geometry}
            material={materials.Band}
            position={[-34.989, 0.544, 3.702]}
            rotation={[-Math.PI, -0.482, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_59.geometry}
            material={materials.Band}
            position={[-33.918, -2.731, -1.799]}
            rotation={[-Math.PI, -0.482, -Math.PI]}
          />
        </group>
      </group>
      <group position={[-0.285, -2.864, -0.026]} scale={[4.373, 1.758, 4.373]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_61.geometry}
          material={materials.Cake}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_62.geometry}
          material={materials.Band}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.material_0}
        position={[-0.757, 1.215, 1.499]}
        rotation={[-0.015, 1.571, 0]}
        scale={1.728}
      />
    </group>
  )
}

useGLTF.preload('/cake_3d.glb')