/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Niraj (https://sketchfab.com/niraj.upadhyay)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/plates-4bc67f865df64d52bdb640a887dc18ae
Title: Plates
*/

import { useGLTF } from '@react-three/drei'

export function Plates(props) {
  const { nodes, materials } = useGLTF('/plates.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.521}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle_Plates001_0.geometry}
            material={materials['Plates.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle001_Plates001_0.geometry}
            material={materials['Plates.001']}
            position={[-113.912, -1.192, -315.595]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/plates.glb')