/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Black Snow (https://sketchfab.com/BlackSnow02)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/plate-519c319332ed4708ba4b3ca1dfd5f54a
Title: Plate
*/

import { useGLTF } from '@react-three/drei'

export function Plate(props) {
  const { nodes, materials } = useGLTF('/plate.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.plate_plate_0.geometry}
          material={materials.plate}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/plate.glb')

