/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Sakura2(props) {
  const { nodes, materials } = useGLTF('/japanese_cherry_tree-compressed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials['Material.002']}
        position={[-2.135, 20.712, -3.73]}
        scale={19.237}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry}
        material={materials.Material}
        position={[-2.312, 19.379, -3.588]}
        scale={19.386}
      />
    </group>
  )
}

useGLTF.preload('/japanese_cherry_tree-compressed.glb')