/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Sereib (https://sketchfab.com/Sereib)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/japanese-cherry-tree-medium-poly-e0306a4402b44fa08f55aa58518dcb9c
Title: Japanese Cherry Tree (medium-Poly)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Sakura(props) {
  const { nodes, materials } = useGLTF('/japanese_cherry_tree_medium-poly_optimized.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials['nature_bark_cherry_02_l_0001.jpg']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials['nature_blossoms_prunusserrulata_01_l_0001.jpg']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials['nature_blossoms_prunusserrulata_01_l_0002.jpg']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials['nature_blossoms_prunusserrulata_01_l_0003.jpg']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials['nature_blossoms_prunusserrulata_01_l_0004.jpg']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials['nature_blossoms_prunusserrulata_01_l_0005.jpg']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials['nature_blossoms_prunusserrulata_01_l_0006.jpg']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/japanese_cherry_tree_medium-poly_optimized.glb')