/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: OfekDavid (https://sketchfab.com/OfekDavid)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tables-and-chairs-7193b868ef684578afd230a59ef9be8f
Title: Tables And Chairs
*/

import { useGLTF } from '@react-three/drei'

export function TablesAndChairs(props) {
  const { nodes, materials } = useGLTF('/tables_and_chairs.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[717.132, 167.077, -232.951]} rotation={[-Math.PI / 2, 0, 0]} scale={120}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Chair1_Wood049_2K_0.geometry}
            material={materials.Wood049_2K}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Chair1_Metal028_2K_0.geometry}
            material={materials.Metal028_2K}
          />
        </group>
        <group
          position={[598.735, 167.077, -232.951]}
          rotation={[-Math.PI / 2, 0, -3.016]}
          scale={120}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Chair2_Wood049_2K_0.geometry}
            material={materials.Wood049_2K}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Chair2_Metal028_2K_0.geometry}
            material={materials.Metal028_2K}
          />
        </group>
        <group
          position={[717.132, 167.077, -303.102]}
          rotation={[-Math.PI / 2, 0, 0.238]}
          scale={120}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Chair3_Wood049_2K_0.geometry}
            material={materials.Wood049_2K}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Chair3_Metal028_2K_0.geometry}
            material={materials.Metal028_2K}
          />
        </group>
        <group
          position={[598.735, 167.077, -313.251]}
          rotation={[-Math.PI / 2, 0, 2.737]}
          scale={120}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Chair4_Wood049_2K_0.geometry}
            material={materials.Wood049_2K}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Chair4_Metal028_2K_0.geometry}
            material={materials.Metal028_2K}
          />
        </group>
        <group position={[627.148, 203.377, -224.788]} rotation={[-Math.PI / 2, 0, 0]} scale={120}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Table_Wood049_2K_0.geometry}
            material={materials.Wood049_2K}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Table_Metal028_2K_0.geometry}
            material={materials.Metal028_2K}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tables_and_chairs.glb')

