/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Blaine Frazier (https://sketchfab.com/bncorley)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wooden-floor-1296c1bfec1242f79e8fec4dccf8b3cd
Title: Wooden Floor
*/

import { useGLTF } from '@react-three/drei'

export function WoodenFloor2(props) {
  const { nodes, materials } = useGLTF('/wooden_floor.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_Floor_01_Mat_Floor_0.geometry}
          material={materials.Mat_Floor}
          position={[1004.858, -392.112, 264.277]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/wooden_floor.glb')