/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Tijerín Art Studio (https://sketchfab.com/tijerin_art)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-tile-wooden-floor-texture-126ecdb451ef4ee2a622ccc748746709
Title: Old tile wooden floor texture
*/

import { useGLTF } from '@react-three/drei'

export function WoodenFloor(props) {
  const { nodes, materials } = useGLTF('/old_tile_wooden_floor_texture_optimized.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.initialShadingGroup}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/old_tile_wooden_floor_texture_optimized.glb')